[package]
name = "sapphire-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
git2 = "0.18.3"

[[bin]]
name = "sapphire"
path = "src/main.rs"
