name: Release Crosspost

on:
  release:
    types:
      - published

jobs:
  Crosspost:
    name: Release Crosspost
    runs-on: ubuntu-latest
    steps:
      - name: Parse release name
        id: get_release_name
        run: echo "release_name=${RELEASE:-$TAG}" >> $GITHUB_OUTPUT
        env:
          RELEASE: ${{ github.event.release.name }}
          TAG: ${{ github.event.release.tag_name }}

      - name: Send Release Message
        id: crosspost_action
        uses: kludge-cs/gitcord-release-changelogger@5592170408dc081d7cb6a74ce025911bd1fcb7c3 # renovate: tag=v3.0.0
        with:
          webhook-url: ${{ secrets.RELEASE_WEBHOOK }}
          release-body: ${{ github.event.release.body }}
          release-name: ${{ steps.get_release_name.outputs.release_name }}
