name: Vuepress Deploy

on:
  push:
    branches:
      - vuepress
  workflow_dispatch: {}

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          ref: vuepress
      - name: Install Node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: "yarn run docs:build"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@0f24da7de3e7e135102609a4c9633b025be8411b # renovate: tag=4.1.5
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
